version: "3"

services:
  cloudflared:
    container_name: cloudflared
    image: knight/cloudflared-dns:arm
    restart: unless-stopped
    ports:
      - "54:54/udp"
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pi-hole:
    container_name: pi-hole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /home/pi/pihole/whitelist.txt:/etc/pihole/whitelist.txt:rw
    depends_on:
      - cloudflared
    env_file:
      - "external-vars.env"
    environment:
      - ServerIP=10.0.0.3
      - DNS1='10.0.0.2#54'
      - DNS2=''
      - IPv6=false
      - TZ=CEST-2
      - DNSMASQ_LISTENING=all
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN

networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
